### ISSUE TITLE
跑测试报错java.lang.NoClassDefFoundError: org/apache/hadoop/mapreduce/Job

### ISSUE THREAD

**Issue by glfeng318** [ruoyu-chen/hadoop-docker#16]
![wx20180302-171432](https://user-images.githubusercontent.com/394134/36891716-75e8c186-1e3d-11e8-930f-98435d1053d3.png)

**Comment by naiba** [comment]
请问一下，build的时候lfs文件怎么搞的

**Comment by naiba** [comment]
已经移除需要lfs的文件， naiba/hadoop-docker@ed081da
