### ISSUE TITLE
编译时报错，提示hadoop-2.7.2.tar.gz not in gzip format

### ISSUE THREAD

**Issue by ripingit** [ruoyu-chen/hadoop-docker#2]
你好，我在编译hadoop时会报如下错误
gzip: stdin: not in gzip format
tar: Child returned status 1
tar: Error is not recoverable: exiting now
ERROR: Service 'hadoop' failed to build: The command '/bin/sh -c wget https://github.com/ruoyu-chen/hadoop-docker/raw/master/dist/hadoop-2.7.2.tar.gz &&  tar -xzvf hadoop-2.7.2.tar.gz -C /root/ &&     mv /root/hadoop-2.7.2 $HADOOP_HOME &&     rm -rf hadoop-2.7.2.tar.gz &&     rm -rf $HADOOP_HOME/bin/*.cmd &&     rm -rf $HADOOP_HOME/sbin/*.cmd &&     rm -rf $HADOOP_HOME/sbin/*all* &&     rm -rf $HADOOP_CONF_DIR/*.cmd &&     rm -rf $HADOOP_CONF_DIR/*.template &&     rm -rf $HADOOP_CONF_DIR/*.example &&     wget https://github.com/ruoyu-chen/hadoop-docker/raw/master/dist/protobuf.tar.gz &&      tar -xzvf protobuf.tar.gz -C /root/ &&       rm -rf protobuf.tar.gz' returned a non-zero code: 2

我手动解压远dist目录下的gz包和用命令手动下载的包都报同样的错误，请问是不是那个文件有不完整导致的？

**Comment by ruoyu-chen** [comment]
这个项目中大部分的tar.gz文件是以LFS的形式存储在GitHub上的，因此需要从GitHub上下载才可以编译镜像。下载的源代码包里的这些文件只是一个占位符。
另外，我已经将镜像推送到docker hub上了，可以不必编译镜像，直接从docker hub 上下载，说明见
https://github.com/ruoyu-chen/hadoop-docker/tree/centos7


------------------
祝：工作顺利、身体健康
 陈若愚
 北京信息科技大学
 计算机学院
 邮箱:
 ruoyu-chen@foxmail.com
twinsen.ruoyu@gmail.com
 ruoyu-chen@163.com
  
 Ruoyu Chen
  School of Computer Science

 Beijing Information Science & Technology University
 E-mail:
  ruoyu-chen@foxmail.com
 twinsen.ruoyu@gmail.com

 ruoyu-chen@163.com


 




------------------ 原始邮件 ------------------
发件人: "ripingit";<notifications@github.com>;
发送时间: 2017年3月29日(星期三) 下午2:03
收件人: "ruoyu-chen/hadoop-docker"<hadoop-docker@noreply.github.com>; 
抄送: "Subscribed"<subscribed@noreply.github.com>; 
主题: [ruoyu-chen/hadoop-docker] 编译时报错，提示hadoop-2.7.2.tar.gz not in gzip format (#2)




你好，我在编译hadoop时会报如下错误
 gzip: stdin: not in gzip format
 tar: Child returned status 1
 tar: Error is not recoverable: exiting now
 ERROR: Service 'hadoop' failed to build: The command '/bin/sh -c wget https://github.com/ruoyu-chen/hadoop-docker/raw/master/dist/hadoop-2.7.2.tar.gz &&  tar -xzvf hadoop-2.7.2.tar.gz -C /root/ &&     mv /root/hadoop-2.7.2 $HADOOP_HOME &&     rm -rf hadoop-2.7.2.tar.gz &&     rm -rf $HADOOP_HOME/bin/.cmd &&     rm -rf $HADOOP_HOME/sbin/.cmd &&     rm -rf $HADOOP_HOME/sbin/all &&     rm -rf $HADOOP_CONF_DIR/.cmd &&     rm -rf $HADOOP_CONF_DIR/.template &&     rm -rf $HADOOP_CONF_DIR/*.example &&     wget https://github.com/ruoyu-chen/hadoop-docker/raw/master/dist/protobuf.tar.gz &&      tar -xzvf protobuf.tar.gz -C /root/ &&       rm -rf protobuf.tar.gz' returned a non-zero code: 2
 
我手动解压远dist目录下的gz包和用命令手动下载的包都报同样的错误，请问是不是那个文件有不完整导致的？
