### ISSUE TITLE
请教下，问什么不用Cloudera平台的Hadoop呢？

### ISSUE THREAD

**Issue by RedMagicVer7** [ruoyu-chen/hadoop-docker#26]
参考了很多其他的Dockerfile，使用Apache原生Hadoop最多，
不过在生产环境CDH用的还是比较多的，想知道为什么用Docker搭建的时候Apache的Hadoop反而更常用了？

**Comment by ruoyu-chen** [comment]
CDH的环境比较复杂，是通过CDH自己的一套软件包管理机制来负责部署、更新和维护的。在我制作docker镜像的时候，希望能够把Hadoop的各个服务都独立出来进行管理，比如Hadoop本身，HBase、Spark等等。所以采用的方法是在原生Hadoop基础上编译的方式。
因为工作比较忙，现在已经不再维护和更新这个hadoop-docker项目了，感谢你的关注。

**Comment by RedMagicVer7** [comment]
感谢您的指点。
