### ISSUE TITLE
README文件内容错误

### ISSUE THREAD

**Issue by RedMagicVer7** [ruoyu-chen/hadoop-docker#28]
有两个branch，一个centos6，一个centos7，但是README文件都是centos6

**Comment by ruoyu-chen** [comment]
centos6和7的主要区别在于centos7使用了systemd进行系统启动时的管理，这个区别对docker镜像的影响比较大，尤其是Hadoop这种需要在镜像启动的时候就启动SSH服务的，所以曾经想升级到centos7但因为时间精力等各种原因放弃了。
因为工作比较忙，现在已经不再维护和更新这个hadoop-docker项目了，感谢你的关注。

**Comment by RedMagicVer7** [comment]
感谢作者指点。
