### ISSUE TITLE
请问是如何实现container的IP持久化的

### ISSUE THREAD

**Issue by VincentXWD** [ruoyu-chen/hadoop-docker#8]
如题，启动一个container时docker会自动分配一个IP，请问您是如何保证master存的三个slave的映射不变的呢？

**Comment by ruoyu-chen** [comment]
使用docker-compose工具。docker-compose.yml文件，可以指定集群中节点所在的网络，同时可以指定他们在该网络内部的主机名，所以hadoop是根据主机名来访问slave的，而不是IP地址，因此就没问题了。即使地址变了，只要主机名不变就没事。

**Comment by VincentXWD** [comment]
明白啦，谢谢老师(*/ω＼*)
